language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer self-update
    - composer install --prefer-source --dev

script:
    - ./vendor/bin/phpcs app/ -n --standard=./phpcs.xml --ignore=app/database --ignore=app/views
    # - ./vendor/bin/phpcpd app/ --verbose
    - ./vendor/bin/phpmd app/ text design,naming,unusedcode,controversial --exclude "migrations"
    - phpunit

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
