language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer self-update
    - composer install --prefer-source --dev

script:
    - ./vendor/bin/phpcs src/ tests/ --standard=PSR2 -n
    # - ./vendor/bin/phpcpd src/ tests/ --verbose
    # - ./vendor/bin/phpmd src/,tests/ text design,naming,unusedcode,controversial,codesize
    # - ./vendor/bin/phploc src/
    - phpunit